[package]
name = "example-esp32s3"
version = "0.1.0"
edition = "2024"

[dependencies]
zenoh-nostd = { version = "1.5.1", path = "../../.." }
zenoh-nostd-embassy  = { version = "1.5.1", path = ".." }

getrandom = { version = "0.2.16", features = ["custom"] }

esp-bootloader-esp-idf = { version = "0.2.0", features = ["esp32s3"] }

esp-hal = { version = "=1.0.0-rc.1", features = [
  "defmt",
  "esp32s3",
  "unstable",
] }

embassy-net = { version = "0.7.1", features = [
  "defmt",
  "dhcpv4",
  "medium-ethernet",
  "tcp",
] }

# embedded-io = { version = "0.6.1", features = ["defmt-03"] }
# embedded-io-async = { version = "0.6.1", features = ["defmt-03"] }

esp-alloc = { version = "0.9.0", features = ["defmt"] }
esp-println = { version = "0.15.0", features = ["defmt-espflash", "esp32s3"] }

# for more networking protocol support see https://crates.io/crates/edge-net
# critical-section = "1.2.0"
embassy-executor = { version = "0.9.1", features = [
  "defmt",
] }

embassy-time = { version = "0.5.0", features = ["defmt"] }

esp-rtos = { version = "0.1.1", features = ["esp32s3", "esp-radio", "embassy"] }

esp-radio = { version = "0.16.0", features = [
  "unstable",
  "defmt",
  "esp-alloc",
  "esp32s3",
  "smoltcp",
  "wifi",
] }

defmt = "1.0.1"

# smoltcp = { version = "0.12.0", default-features = false, features = [
#   "defmt",
#   "medium-ethernet",
#   "multicast",
#   "proto-dhcpv4",
#   "proto-dns",
#   "proto-ipv4",
#   "socket-dns",
#   "socket-icmp",
#   "socket-raw",
#   "socket-tcp",
#   "socket-udp",
# ] }

static_cell = "2.1.1"
heapless = { version = "0.9.1" }
embassy-sync = { version = "0.7.0", features = ["defmt"] }

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units    = 1     # LLVM can perform better optimizations using a single thread
debug            = 2
debug-assertions = false
incremental      = false
lto              = 'fat'
opt-level        = 's'
overflow-checks  = false
